leveldb: add slow downed and paused write statistic
syndtr/goleveldb pull request #193
Opened 2017-12-11 05:15 UTC by rjl493456442

Implements #181

2017-12-11 05:16 UTC, rjl493456442 commented
@syndtr  PTAL :)

2017-12-13 08:06 UTC, syndtr requested changes

2017-12-13 08:06 UTC, syndtr commented on leveldb/db.go
> +	writeDelayStat         *wDelayStat
I think we can just unpack `wDelayStat` struct into DB struct. Also I think using `sync/atomic` is enough (yes, inconsistency between counter and timer might happen but I think that's not a big issue in this case), you can cast `time.Duration` to `int64`.

2017-12-13 08:11 UTC, syndtr approved these changes

2017-12-13 08:14 UTC, syndtr requested changes
I think we can just unpack `wDelayStat` struct into DB struct. Also I think using `sync/atomic` is enough (yes, inconsistency between counter and timer might happen but I think that's not a big issue in this case), you can cast `time.Duration` to `int64`.

2017-12-13 08:30 UTC, rjl493456442 commented
@syndtr Updated!

2017-12-14 12:27 UTC, syndtr commented
Merged at 34011bf325bce385408353a30b101fe5e923eb6e. Thanks!

2017-12-14 12:27 UTC, closed without merging