Support a sharing lru cache.
syndtr/goleveldb pull request #230
Opened 2018-08-15 20:27 UTC by gaillard

Fixes #228

2018-08-17 22:03 UTC, gaillard commented
Any concerns here?

2021-07-25 06:18 UTC, tgulacsi requested changes

2021-07-25 06:18 UTC, tgulacsi commented on .travis.yml
>  language: go
Please do not change .travis.yml in thisn commit!

2021-07-25 06:18 UTC, tgulacsi commented on leveldb/cache/lru.go
> +// NewLRU create a new namespaced LRU-cache.
The comment should start with the function's name.

2021-07-25 06:18 UTC, tgulacsi commented on leveldb/cache/lru.go
> +//nodeNS optional.
```
// evictMulti evicts multiple nodes
// nodeNS is optional
```

2021-07-25 06:18 UTC, tgulacsi commented on leveldb/cache/lru.go
> +	lruNS byte
Change the order to `*SharedLRU,byte` to save on alignment.

2022-06-13 04:53 UTC, syndtr commented
Superseded by 4bbca4ea2470b1c244f502710f0cc52023ba0e44.

2022-06-13 04:53 UTC, closed without merging